# Generated by Django 3.1.2 on 2020-11-04 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20201104_0757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='users',
        ),
    ]
